### ISSUE TITLE
Gracefully handle refused connections in MQ-interceptor

### ISSUE THREAD

**Issue by kjetilkl** [ELIXIR-NO/FEGA-Norway#176]
If the [dialRabbitMQ](https://github.com/ELIXIR-NO/FEGA-Norway/blob/e4426b509cf24f1de9fc6c3b267e5c482e5a2623/services/mq-interceptor/main.go#L25-L51) method is unable to connect to an MQ instance even after 10 tries, it returns a [`nil` connection object and an error](https://github.com/ELIXIR-NO/FEGA-Norway/blob/e4426b509cf24f1de9fc6c3b267e5c482e5a2623/services/mq-interceptor/main.go#L50). But the error is not checked before using the connection to LEGA MQ [here](https://github.com/ELIXIR-NO/FEGA-Norway/blob/e4426b509cf24f1de9fc6c3b267e5c482e5a2623/services/mq-interceptor/main.go#L61-L62), which causes the MQ-interceptor to crash.  (However, it is checked when connecting to CEGA MQ [here](https://github.com/ELIXIR-NO/FEGA-Norway/blob/e4426b509cf24f1de9fc6c3b267e5c482e5a2623/services/mq-interceptor/main.go#L73-L75))
```
2024/05/31 10:48:48 Attempt 1: Failed to connect to RabbitMQ: dial tcp: lookup mq on 127.0.0.11:53: no such host
2024/05/31 10:48:50 Attempt 2: Failed to connect to RabbitMQ: dial tcp: lookup mq on 127.0.0.11:53: no such host
2024/05/31 10:48:52 Attempt 3: Failed to connect to RabbitMQ: dial tcp: lookup mq on 127.0.0.11:53: no such host
2024/05/31 10:48:54 Attempt 4: Failed to connect to RabbitMQ: dial tcp: lookup mq on 127.0.0.11:53: no such host
2024/05/31 10:48:56 Attempt 5: Failed to connect to RabbitMQ: dial tcp: lookup mq on 127.0.0.11:53: no such host
2024/05/31 10:48:58 Attempt 6: Failed to connect to RabbitMQ: dial tcp: lookup mq on 127.0.0.11:53: no such host
2024/05/31 10:49:00 Attempt 7: Failed to connect to RabbitMQ: dial tcp: lookup mq on 127.0.0.11:53: no such host
2024/05/31 10:49:02 Attempt 8: Failed to connect to RabbitMQ: dial tcp: lookup mq on 127.0.0.11:53: no such host
2024/05/31 10:49:04 Attempt 9: Failed to connect to RabbitMQ: dial tcp: lookup mq on 127.0.0.11:53: no such host
2024/05/31 10:49:06 Attempt 10: Failed to connect to RabbitMQ: dial tcp: lookup mq on 127.0.0.11:53: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x62e591]

goroutine 1 [running]:
github.com/rabbitmq/amqp091-go.(*Connection).allocateChannel(0x0)
      /root/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.9.0/connection.go:812 +0x51
github.com/rabbitmq/amqp091-go.(*Connection).openChannel(0xc000020013?)
      /root/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.9.0/connection.go:847 +0x1c
github.com/rabbitmq/amqp091-go.(*Connection).Channel(...)
      /root/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.9.0/connection.go:873
main.main()
      /go/main.go:70 +0x12c
```

**Comment by kjetilkl** [comment]
Fixed by Yasin in PR #178
